// function fetc(){
//     return new Promise((resolve, reject) => {
//         setTimeout(() => {
//             resolve("resolved succesfully")
//         }, 10000);
        
//     })
// }




// // function getdata(){
// //     fetc().then(function(data){
// //         console.log(data)                    //namastejs  will print first
// //                                                // and then promise will resolve

// //                                                //in this case the regular mechanishm applies 
// //     })                                 
// //     console.log("namaste js")
// // }




// async function getdata(){
//     const p1=await fetc()
//     console.log("namastejs1")
//     console.log(p1)              // in this case after the promise gets resolved only it will print namaste js 
     
    
    
//                                          // so here when the js engine encounters await
// //         it will suspend the exec of the whole function and attach callback function to webapi and after resolving the promise it will push call ba 
// //  promise gets resolved and after
// //                                     that the function gets resumed at the same line at which it stopped first  

//   }

// getdata();
















